---
# Install ntp packages

- name: unwanted packages are removed
  package:
    name: "{{ ntp_packages_remove }}"
    state: absent
  become: true
  when: ntp_remove_packages

- name: prereq repositories are installed
  package:
    name: "{{ ntp_packages_repos }}"
    state: "{{ ntp_packages_state }}"
  become: true

- name: prereq packages are installed
  package:
    name: "{{ ntp_packages_prereq }}"
    state: "{{ ntp_packages_state }}"
  become: true

- name: packages are installed
  package:
    name: "{{ ntp_packages_install }}"
    state: "{{ ntp_packages_state }}"
  become: true
