---
# Template configuration files for ntp

- name: template is copied
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  become: true
  loop: "{{ ntp_templates_copy }}"
  when: ntp_copy_templates
